version: "2"
services:
  boilerplate-api:
    command: yarn dev -- -L
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"